### ISSUE TITLE
Unable to parse input JSON

### ISSUE THREAD

**Issue by alfonpd** [EOSC-synergy/eosc-perf-benchmarks#1]
I get the next error when benchmark finish:

```
Unable to parse input JSON!



Phoronix Test Suite v10.0.1
An outdated version of the Phoronix Test Suite is installed.
The version in use is 10.0.1 (10010), but the latest is pts-core 10810.
Visit https://www.phoronix-test-suite.com/ to update this software.

{
    "title": "resultdata",
    "results": [
        {
            "test": "pts\/c-ray-1.2.0",
            "arguments": "Total Time - 4K, 16 Rays Per Pixel",
            "units": "Seconds",
            "results": {
                "test_result": {
                    "value": "546.696",
                    "all_results": "532.65:548.734:558.704"
                }
            }
        }
    ]
}


Traceback (most recent call last):
  File "/extract_and_add_meta.py", line 43, in <module>
    main()
  File "/extract_and_add_meta.py", line 26, in main
    data = in_data["results"][0]

```

These are the steps I did after creating the machine "EOSC-Synergy benchmark virtual machine" from IM-Dashboard:

_#> cd $HOME
#> mkdir out
#> docker run -v $(pwd)/out:/out_dir thechristophe/openbench-c-ray_

**Comment by TheChristophe** [comment]
It seems the issue is that the phoronix test suite displays the update banner when requesting just the json (why???), so the script that adds CPU metadata fails to parse it

**Comment by TheChristophe** [comment]
Luckily a new version of phoronix test suite provides the ability to write it to a file directly without having to redirect outputs, hopefully avoiding other such issues in the future. Unfortunately, the json output structure changed somewhat, too.
Please try with the new image: perfbench/openbench-c-ray:v1
I likely will have to re-run the tests on all other sites...

**Comment by alfonpd** [comment]
Hi, 

The new image now generate the JSON file, but when I try to sumbit the restult to the EOSC-Perf website (https://performance.services.fedcloud.eu/result-submission#) I get an error:

```
Error: Server could not process our submission:

{
    "code": 422,
    "errors": {
        "error": "'arguments' is a required property",
        "path": "deque([])"
    },
    "status": "Unprocessable Entity"
}

Your input may be malformed or wrong, please verify if everything is correct. If you believe this to be a bug, please submit an issue about it on [GitHub](https://github.com/EOSC-synergy/eosc-perf/issues)!
```

**Comment by TheChristophe** [comment]
You may have submitted it under thechristophe/openbench-c-ray, which has a different schema so results from perfbench/openbench-c-ray are not compatible. I have not yet added perfbench/openbench-c-ray, because so far most of the machines I've been able to deploy on IM did not work correctly so I could gather data.

**Comment by alfonpd** [comment]
Ok, I understand it.

I await you upload perfbench/openbench-c-ray or change the thechristophe/openbench-c-ray with the changes that correct the json output file.

regards

**Comment by TheChristophe** [comment]
It seems I've forgotten about this issue, oops.

The image is published at https://hub.docker.com/repository/docker/perfbench/openbench-c-ray.
Instructions on running it are available at https://github.com/EOSC-synergy/eosc-perf-benchmarks/blob/main/phoronix-c-ray-docker/README.md.
